export const data = {
  status: "OK",
  copyright:
    "Copyright (c) 2025 The New York Times Company.  All Rights Reserved.",
  num_results: 20,
  results: [
    {
      uri: "nyt://article/b2b59052-2ff9-5a63-99fb-29c7b073b40c",
      url: "https://www.nytimes.com/2025/03/04/world/europe/ukraine-us-trump-military-support.html",
      id: 100000010029938,
      asset_id: 100000010029938,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 08:21:38",
      section: "World",
      subsection: "Europe",
      nytdsection: "world",
      adx_keywords:
        "Russian Invasion of Ukraine (2022);United States International Relations;Defense and Military Forces;Foreign Aid;Missiles and Missile Defense Systems;Arms Trade;Trump, Donald J;Zelensky, Volodymyr;von der Leyen, Ursula;European Union;Ukraine;Russia;United States;Europe",
      column: null,
      byline: "By Marc Santora",
      type: "Article",
      title:
        "Zelensky Offers Terms to Stop Fighting, Assuring U.S. That Ukraine Wants Peace",
      abstract:
        "“We are working on all possible scenarios to protect Ukraine,” said President Volodymyr Zelensky, whose country was looking to European allies for support.",
      des_facet: [
        "Russian Invasion of Ukraine (2022)",
        "United States International Relations",
        "Defense and Military Forces",
        "Foreign Aid",
        "Missiles and Missile Defense Systems",
        "Arms Trade",
      ],
      org_facet: ["European Union"],
      per_facet: [
        "Trump, Donald J",
        "Zelensky, Volodymyr",
        "von der Leyen, Ursula",
      ],
      geo_facet: ["Ukraine", "Russia", "United States", "Europe"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Members of Ukraine’s 38th Separate Marine Brigade in the Pokrovsk region in November. It’s not clear how long Ukraine’s stockpiles will last before there are critical gaps on the front.",
          copyright: "Tyler Hicks/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04ukraine-diplomacy-01-qwcf/04ukraine-diplomacy-01-qwcf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04ukraine-diplomacy-01-qwcf/04ukraine-diplomacy-01-qwcf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04ukraine-diplomacy-01-qwcf/04ukraine-diplomacy-01-qwcf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/5bb389c3-d9e8-53ee-b986-5d25e4cf890d",
      url: "https://www.nytimes.com/2025/03/04/us/politics/jd-vance-uk-random-country.html",
      id: 100000010030238,
      asset_id: 100000010030238,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 15:29:31",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "United States International Relations;Defense and Military Forces;Trump, Donald J;Starmer, Keir;Macron, Emmanuel (1977- );North Atlantic Treaty Organization;France;Great Britain;Ukraine;Europe;Russia",
      column: null,
      byline: "By Mark Landler",
      type: "Article",
      title: "Vance Ignites Outrage in Britain With ‘Random Country’ Comment",
      abstract:
        "The vice president denied that he was talking about Britain and France when he downplayed “20,000 troops from some random country” protecting Ukraine. No other countries have pledged troops.",
      des_facet: [
        "United States International Relations",
        "Defense and Military Forces",
      ],
      org_facet: ["North Atlantic Treaty Organization"],
      per_facet: [
        "Trump, Donald J",
        "Starmer, Keir",
        "Macron, Emmanuel (1977- )",
      ],
      geo_facet: ["France", "Great Britain", "Ukraine", "Europe", "Russia"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Vice President JD Vance’s comments on the Anglo-French proposal to protect Ukraine have sparked criticism in Britain.",
          copyright: "Kenny Holston/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04trump-news-vance-uk-cjqf/04trump-news-vance-uk-cjqf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04trump-news-vance-uk-cjqf/04trump-news-vance-uk-cjqf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04trump-news-vance-uk-cjqf/04trump-news-vance-uk-cjqf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/cedce6ab-1376-5140-8acc-a4af54791b97",
      url: "https://www.nytimes.com/2025/03/03/us/carl-dean-dead.html",
      id: 100000010029370,
      asset_id: 100000010029370,
      source: "New York Times",
      published_date: "2025-03-03",
      updated: "2025-03-04 12:19:47",
      section: "U.S.",
      subsection: "",
      nytdsection: "u.s.",
      adx_keywords:
        "Country Music;Deaths (Obituaries);Dean, Carl (1942-2025);Parton, Dolly;Nashville (Tenn)",
      column: null,
      byline: "By Sara Ruberg and Alexandra E. Petri",
      type: "Article",
      title: "Carl Dean, Dolly Parton’s Husband of Nearly 60 Years, Dies at 82",
      abstract:
        "Mr. Dean, who inspired songs including “Jolene” and “From Here to the Moon and Back,” was known to shy away from the spotlight as his wife rose to fame.",
      des_facet: ["Country Music", "Deaths (Obituaries)"],
      org_facet: [],
      per_facet: ["Dean, Carl (1942-2025)", "Parton, Dolly"],
      geo_facet: ["Nashville (Tenn)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Carl Dean, who was married to Dolly Parton for nearly 60 years, died on Monday.",
          copyright: "Instagram",
          approved_for_syndication: 0,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/03/arts/03xp-dean/03xp-dean-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/arts/03xp-dean/03xp-dean-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/arts/03xp-dean/03xp-dean-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/aafd9685-03ab-5272-9537-4fb66b1e44b2",
      url: "https://www.nytimes.com/2025/03/04/opinion/trump-imperial-presidency.html",
      id: 100000010028132,
      asset_id: 100000010028132,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 14:27:08",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "United States Politics and Government;Presidential Power (US);Presidential Election of 2024;Immunity from Prosecution;Law and Legislation;Trump, Donald J;Republican Party;Supreme Court (US)",
      column: null,
      byline: "By Thomas B. Edsall",
      type: "Article",
      title: "‘Trump Is the Real Thing’",
      abstract: "Vengeance is his.",
      des_facet: [
        "United States Politics and Government",
        "Presidential Power (US)",
        "Presidential Election of 2024",
        "Immunity from Prosecution",
        "Law and Legislation",
      ],
      org_facet: ["Republican Party", "Supreme Court (US)"],
      per_facet: ["Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Don Farrall/Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/opinion/04edsall/04edsall-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/opinion/04edsall/04edsall-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/opinion/04edsall/04edsall-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://interactive/eeaaeac6-1ffc-52dd-bac2-74c4cf70cc08",
      url: "https://www.nytimes.com/interactive/2025/03/04/polls/tariffs-trump-poll.html",
      id: 100000010028909,
      asset_id: 100000010028909,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 10:16:26",
      section: "Polls",
      subsection: "",
      nytdsection: "polls",
      adx_keywords:
        "Protectionism (Trade);Polls and Public Opinion;International Trade and World Market;United States Politics and Government;Trump, Donald J;Ipsos SA;YouGov",
      column: null,
      byline: "By Christine Zhang and Ruth Igielnik",
      type: "Interactive",
      title: "How Americans Feel About Tariffs",
      abstract:
        "Trump loves tariffs. Do Americans? It depends how pollsters ask the question.",
      des_facet: [
        "Protectionism (Trade)",
        "Polls and Public Opinion",
        "International Trade and World Market",
        "United States Politics and Government",
      ],
      org_facet: ["Ipsos SA", "YouGov"],
      per_facet: ["Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "",
          caption: "",
          copyright: "The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/03/multimedia/2025-02-24-tariff-polls-index/2025-02-24-tariff-polls-index-thumbStandard-v7.png",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/multimedia/2025-02-24-tariff-polls-index/2025-02-24-tariff-polls-index-mediumThreeByTwo210-v7.png",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/multimedia/2025-02-24-tariff-polls-index/2025-02-24-tariff-polls-index-mediumThreeByTwo440-v7.png",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/65857463-3f65-5ab9-a022-2562d6d39886",
      url: "https://www.nytimes.com/2025/03/04/us/politics/supreme-court-epa-water.html",
      id: 100000010011699,
      asset_id: 100000010011699,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 00:05:47",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Clean Water Act;Water;Law and Legislation;Fines (Penalties);Alito, Samuel A Jr;Environmental Protection Agency;Supreme Court (US)",
      column: null,
      byline: "By Abbie VanSickle and Adam Liptak",
      type: "Article",
      title:
        "Supreme Court Deals Blow to E.P.A. in Dispute Over Federal Water Rules",
      abstract:
        "The 5-to-4 decision is the latest setback for the agency and could have sweeping implications for curtailing water pollution offshore.",
      des_facet: [
        "Clean Water Act",
        "Water",
        "Law and Legislation",
        "Fines (Penalties)",
      ],
      org_facet: ["Environmental Protection Agency", "Supreme Court (US)"],
      per_facet: ["Alito, Samuel A Jr"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "The question before the court was whether the Clean Water Act of 1972 allowed the E.P.A. to impose prohibitions on wastewater released into the Pacific Ocean and to penalize San Francisco for violating them.",
          copyright: "Loren Elliott for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04dc-scotus-topart-jhgv/04dc-scotus-topart-jhgv-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04dc-scotus-topart-jhgv/04dc-scotus-topart-jhgv-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04dc-scotus-topart-jhgv/04dc-scotus-topart-jhgv-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/d6e7fe51-9cd9-5d9a-bc84-c58759b40c2e",
      url: "https://www.nytimes.com/2025/03/04/business/stock-market-today-trump-tariffs.html",
      id: 100000010030027,
      asset_id: 100000010030027,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 00:19:18",
      section: "Business",
      subsection: "",
      nytdsection: "business",
      adx_keywords:
        "International Trade and World Market;Protectionism (Trade);United States International Relations;Stocks and Bonds;Standard & Poor's 500-Stock Index;Customs (Tariff);Euro (Currency);Rheinmetall AG;Volkswagen AG",
      column: null,
      byline: "By Joe Rennison, Eshe Nelson and Melissa Eddy",
      type: "Article",
      title: "Trade War Sends a Shiver Through Global Markets",
      abstract:
        "Wall Street has wiped out the gains made since President Trump’s election victory, as investors’ hopes of business-friendly policies have given way to fears over tariffs.",
      des_facet: [
        "International Trade and World Market",
        "Protectionism (Trade)",
        "United States International Relations",
        "Stocks and Bonds",
        "Standard & Poor's 500-Stock Index",
        "Customs (Tariff)",
        "Euro (Currency)",
      ],
      org_facet: ["Rheinmetall AG", "Volkswagen AG"],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Timothy A. Clary/Agence France-Presse — Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04STOCKS-tvwc/04STOCKS-tvwc-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04STOCKS-tvwc/04STOCKS-tvwc-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04STOCKS-tvwc/04STOCKS-tvwc-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://interactive/ab9ecf64-bcd6-5c1a-87bb-f8d71cefd576",
      url: "https://www.nytimes.com/interactive/2025/03/04/opinion/covid-impact-five-years-later.html",
      id: 100000010011464,
      asset_id: 100000010011464,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 08:41:40",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "Coronavirus (2019-nCoV);United States Politics and Government;United States Economy;Social Conditions and Trends;Deaths (Fatalities);Quarantines;Disease Rates;Biden, Joseph R Jr;Trump, Donald J;United States",
      column: null,
      byline: "By David Wallace-Wells",
      type: "Interactive",
      title: "How Covid Remade America",
      abstract:
        "It feels as if the pandemic is behind us. But we’re living in the world it made.",
      des_facet: [
        "Coronavirus (2019-nCoV)",
        "United States Politics and Government",
        "United States Economy",
        "Social Conditions and Trends",
        "Deaths (Fatalities)",
        "Quarantines",
        "Disease Rates",
      ],
      org_facet: [],
      per_facet: ["Biden, Joseph R Jr", "Trump, Donald J"],
      geo_facet: ["United States"],
      media: [
        {
          type: "image",
          subtype: "",
          caption: "",
          copyright: "",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/03/opinion/covid-anniversary-cinemagraph23-still/covid-anniversary-cinemagraph23-still-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/opinion/covid-anniversary-cinemagraph23-still/covid-anniversary-cinemagraph23-still-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/opinion/covid-anniversary-cinemagraph23-still/covid-anniversary-cinemagraph23-still-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/97018aeb-990d-57be-989b-2e3ad06666e5",
      url: "https://www.nytimes.com/2025/03/04/health/texas-measles-outbreak-kennedy.html",
      id: 100000010030135,
      asset_id: 100000010030135,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 17:47:33",
      section: "Health",
      subsection: "",
      nytdsection: "health",
      adx_keywords:
        "your-feed-science;Disease Rates;Vaccination and Immunization;Epidemics;Children and Childhood;Medicine and Health;Mennonite Churches;Measles;Kennedy, Robert F Jr;Health and Human Services Department;Gaines County (Tex)",
      column: null,
      byline: "By Teddy Rosenbluth",
      type: "Article",
      title: "As Measles Spreads, Kennedy Embraces Remedies Like Cod Liver Oil",
      abstract:
        "In an interview, the H.H.S. secretary claimed that unconventional treatments were helping patients but did not mention vaccination.",
      des_facet: [
        "your-feed-science",
        "Disease Rates",
        "Vaccination and Immunization",
        "Epidemics",
        "Children and Childhood",
        "Medicine and Health",
        "Mennonite Churches",
        "Measles",
      ],
      org_facet: ["Health and Human Services Department"],
      per_facet: ["Kennedy, Robert F Jr"],
      geo_facet: ["Gaines County (Tex)"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Billie Armstrong, a family nurse practitioner, prepared a measles, mumps, rubella and varicella vaccine at a Seminole, Texas, hospital on Wednesday amid a measles outbreak. ",
          copyright: "Desiree Rios for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04measles-ltvc/04measles-ltvc-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04measles-ltvc/04measles-ltvc-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04measles-ltvc/04measles-ltvc-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/1561c13c-2974-5ba5-b9df-36ec774786ed",
      url: "https://www.nytimes.com/2025/03/03/style/julia-fox-nude-dress-oscars.html",
      id: 100000010027746,
      asset_id: 100000010027746,
      source: "New York Times",
      published_date: "2025-03-03",
      updated: "2025-03-04 13:38:32",
      section: "Style",
      subsection: "",
      nytdsection: "style",
      adx_keywords:
        "Academy Awards (Oscars);Fashion and Apparel;Parties (Social);Nudism and Nudity;Fox, Julia (1990- );Censori, Bianca;West, Kanye;Findikoglu, Dilara;Kravitz, Zoe;Megan Thee Stallion (Rapper);Pope, Jeremy (Actor);Ratajkowski, Emily;Wilde, Olivia;Chloe (Fashion Label);Monse (Fashion Label);Mugler (Fashion Label)",
      column: null,
      byline: "By Sadiba Hasan",
      type: "Article",
      title: "On Oscars Night, More Celebrities Tried the Nearly Nude Look",
      abstract:
        "Julia Fox followed up Bianca Censori’s much-discussed Grammys moment with a sheer dress at Vanity Fair’s party. Others joined her in the less-is-more approach.",
      des_facet: [
        "Academy Awards (Oscars)",
        "Fashion and Apparel",
        "Parties (Social)",
        "Nudism and Nudity",
      ],
      org_facet: [
        "Chloe (Fashion Label)",
        "Monse (Fashion Label)",
        "Mugler (Fashion Label)",
      ],
      per_facet: [
        "Fox, Julia (1990- )",
        "Censori, Bianca",
        "West, Kanye",
        "Findikoglu, Dilara",
        "Kravitz, Zoe",
        "Megan Thee Stallion (Rapper)",
        "Pope, Jeremy (Actor)",
        "Ratajkowski, Emily",
        "Wilde, Olivia",
      ],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "At Vanity Fair’s Oscars after-party on Sunday night, Julia Fox arrived in a nearly nude maxi dress by the Turkish designer Dilara Findikoglu.",
          copyright: "Neilson Barnard/Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/03/multimedia/03OSCARS-NEARLY-NUDES-hbcl/03OSCARS-NEARLY-NUDES-hbcl-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/multimedia/03OSCARS-NEARLY-NUDES-hbcl/03OSCARS-NEARLY-NUDES-hbcl-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/multimedia/03OSCARS-NEARLY-NUDES-hbcl/03OSCARS-NEARLY-NUDES-hbcl-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/e9bff2b1-2037-5400-91f3-e8ccd0526d8f",
      url: "https://www.nytimes.com/2025/03/04/business/blackrock-panama-canal-ports-hutchison.html",
      id: 100000010030420,
      asset_id: 100000010030420,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 00:21:55",
      section: "Business",
      subsection: "",
      nytdsection: "business",
      adx_keywords:
        "Ports;Mergers, Acquisitions and Divestitures;United States International Relations;Trump, Donald J;CK Hutchison Holdings Ltd;BlackRock Inc;Panama;Panama Canal and Canal Zone;Hong Kong;China",
      column: null,
      byline: "By Peter Eavis and Maureen Farrell",
      type: "Article",
      title:
        "After Trump Applies Pressure, Wall Street Giant Moves Into Panama",
      abstract:
        "An investor group led by BlackRock will acquire two ports near the Panama Canal that are owned by CK Hutchison and have been the subject of a dispute between President Trump and Panama.",
      des_facet: [
        "Ports",
        "Mergers, Acquisitions and Divestitures",
        "United States International Relations",
      ],
      org_facet: ["CK Hutchison Holdings Ltd", "BlackRock Inc"],
      per_facet: ["Trump, Donald J"],
      geo_facet: [
        "Panama",
        "Panama Canal and Canal Zone",
        "Hong Kong",
        "China",
      ],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "A ship crossing the Panama Canal.",
          copyright: "Federico Rios for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04biz-panama-ports-zcvk/04biz-panama-ports-zcvk-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04biz-panama-ports-zcvk/04biz-panama-ports-zcvk-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04biz-panama-ports-zcvk/04biz-panama-ports-zcvk-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/73926ab4-2594-5938-ab0c-381e1123e5be",
      url: "https://www.nytimes.com/2025/03/04/us/politics/trump-trade-war-economy.html",
      id: 100000010030097,
      asset_id: 100000010030097,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 05:29:18",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "International Trade and World Market;United States Politics and Government;Protectionism (Trade);United States Economy;Customs (Tariff);United States International Relations;Drug Abuse and Traffic;Prices (Fares, Fees and Rates);Economic Conditions and Trends;Shopping and Retail;Factories and Manufacturing;Sheinbaum, Claudia;Trudeau, Justin;Trump, Donald J;Commerce Department;European Union;Target Corporation;Republican Party;Canada;China;Mexico;United States",
      column: null,
      byline: "By Alan Rappeport and Ana Swanson",
      type: "Article",
      title: "Trump’s Trade War Could Be His Biggest Economic Gamble",
      abstract:
        "President Trump has offered a mix of reasons for upending global trade relations, baffling and angering America’s biggest trading partners.",
      des_facet: [
        "International Trade and World Market",
        "United States Politics and Government",
        "Protectionism (Trade)",
        "United States Economy",
        "Customs (Tariff)",
        "United States International Relations",
        "Drug Abuse and Traffic",
        "Prices (Fares, Fees and Rates)",
        "Economic Conditions and Trends",
        "Shopping and Retail",
        "Factories and Manufacturing",
      ],
      org_facet: [
        "Commerce Department",
        "European Union",
        "Target Corporation",
        "Republican Party",
      ],
      per_facet: ["Sheinbaum, Claudia", "Trudeau, Justin", "Trump, Donald J"],
      geo_facet: ["Canada", "China", "Mexico", "United States"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "The Port of Los Angeles. President Trump imposed a 25 percent tariff on products from Canada and Mexico and another 10 percent on China.",
          copyright: "Mark Abramson for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04dc-trump-trade-topart-ztmc/04dc-trump-trade-topart-ztmc-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04dc-trump-trade-topart-ztmc/04dc-trump-trade-topart-ztmc-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04dc-trump-trade-topart-ztmc/04dc-trump-trade-topart-ztmc-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/870f0c9d-3940-548c-8a8f-4e9081b1cdfc",
      url: "https://www.nytimes.com/2025/03/04/opinion/ezra-klein-podcast-ben-buchanan.html",
      id: 100000010014594,
      asset_id: 100000010014594,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 15:41:26",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords:
        "Artificial Intelligence;United States Politics and Government;Computers and the Internet;Andreessen, Marc L;Musk, Elon;Biden, Joseph R Jr;Trump, Donald J;Vance, J D;OpenAI Labs;DeepSeek Artificial Intelligence Co Ltd;Anthropic AI LLC;United States",
      column: null,
      byline: "By Ezra Klein",
      type: "Article",
      title: "The Government Knows A.G.I. Is Coming",
      abstract:
        "The Biden administration’s A.I. adviser Ben Buchanan discusses how the U.S. government is preparing for artificial general intelligence — and all the challenges that remain.",
      des_facet: [
        "Artificial Intelligence",
        "United States Politics and Government",
        "Computers and the Internet",
      ],
      org_facet: [
        "OpenAI Labs",
        "DeepSeek Artificial Intelligence Co Ltd",
        "Anthropic AI LLC",
      ],
      per_facet: [
        "Andreessen, Marc L",
        "Musk, Elon",
        "Biden, Joseph R Jr",
        "Trump, Donald J",
        "Vance, J D",
      ],
      geo_facet: ["United States"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/opinion/04eks-buchanan/04eks-buchanan-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/opinion/04eks-buchanan/04eks-buchanan-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/opinion/04eks-buchanan/04eks-buchanan-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/4391d305-379b-59e2-b83d-521ef56c69dc",
      url: "https://www.nytimes.com/2025/03/03/business/tesla-boycott-elon-musk.html",
      id: 100000010005169,
      asset_id: 100000010005169,
      source: "New York Times",
      published_date: "2025-03-03",
      updated: "2025-03-04 12:19:43",
      section: "Business",
      subsection: "",
      nytdsection: "business",
      adx_keywords:
        "Electric and Hybrid Vehicles;Used Cars;Boycotts;Right-Wing Extremism and Alt-Right;United States Politics and Government;Musk, Elon;Trump, Donald J;Tesla Motors Inc;Government Efficiency Department (US)",
      column: null,
      byline: "By Neil Vigdor",
      type: "Article",
      title:
        "Tesla for Sale: Buyer’s Remorse Sinks In for Elon Musk’s E.V.-Owning Critics",
      abstract:
        "The backlash against the electric vehicle company has intensified as the billionaire ally of President Trump exerts his power over the federal government.",
      des_facet: [
        "Electric and Hybrid Vehicles",
        "Used Cars",
        "Boycotts",
        "Right-Wing Extremism and Alt-Right",
        "United States Politics and Government",
      ],
      org_facet: ["Tesla Motors Inc", "Government Efficiency Department (US)"],
      per_facet: ["Musk, Elon", "Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Jennifer Trebb with her Tesla in Pickerington, Ohio. She traded it in over the weekend, after she said she had become “embarrassed” to drive the car.",
          copyright: "Maddie McGarvey for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04xp-tesla-Trebb-01-jpml/04xp-tesla-Trebb-01-jpml-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04xp-tesla-Trebb-01-jpml/04xp-tesla-Trebb-01-jpml-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04xp-tesla-Trebb-01-jpml/04xp-tesla-Trebb-01-jpml-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/9f30f0dc-069a-55f8-82c2-41ff2b6ee0f2",
      url: "https://www.nytimes.com/2025/03/04/us/politics/al-green-trump-speech-heckling.html",
      id: 100000010032240,
      asset_id: 100000010032240,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-05 03:20:43",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "United States Politics and Government;Politics and Government;State of the Union Message (US);Green, Alexander N (1947- );Democratic Party;House of Representatives",
      column: null,
      byline: "By Maya C. Miller",
      type: "Article",
      title:
        "Al Green Removed From House Chamber for Heckling Trump During Address",
      abstract:
        "Republicans had the Texas Democrat, who introduced the first articles of impeachment against Trump in 2017, ejected after he shouted at the president and refused to sit down.",
      des_facet: [
        "United States Politics and Government",
        "Politics and Government",
        "State of the Union Message (US)",
      ],
      org_facet: ["Democratic Party", "House of Representatives"],
      per_facet: ["Green, Alexander N (1947- )"],
      geo_facet: [],
      media: [],
      eta_id: 0,
    },
    {
      uri: "nyt://article/de2f7f85-e8e4-5abf-8d67-4439a0c62eb5",
      url: "https://www.nytimes.com/2025/03/04/briefing/donald-trump-tariffs-canada-mexico-china.html",
      id: 100000010030035,
      asset_id: 100000010030035,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 17:37:43",
      section: "Briefing",
      subsection: "",
      nytdsection: "briefing",
      adx_keywords:
        "internal-storyline-no;United States Politics and Government;Protectionism (Trade);Customs (Tariff);Trump, Donald J;Canada;China;Mexico",
      column: null,
      byline: "By German Lopez",
      type: "Article",
      title: "America’s Flex",
      abstract: "We cover President Trump’s new tariffs.",
      des_facet: [
        "internal-storyline-no",
        "United States Politics and Government",
        "Protectionism (Trade)",
        "Customs (Tariff)",
      ],
      org_facet: [],
      per_facet: ["Trump, Donald J"],
      geo_facet: ["Canada", "China", "Mexico"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "President Trump ",
          copyright: "Doug Mills/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04themorning-nl-Trump-gqlf/04themorning-nl-Trump-gqlf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04themorning-nl-Trump-gqlf/04themorning-nl-Trump-gqlf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04themorning-nl-Trump-gqlf/04themorning-nl-Trump-gqlf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/2b8d8954-8778-56b4-adbf-06dd91330345",
      url: "https://www.nytimes.com/2025/03/03/us/politics/elon-musk-joe-rogan-podcast.html",
      id: 100000010029066,
      asset_id: 100000010029066,
      source: "New York Times",
      published_date: "2025-03-03",
      updated: "2025-03-03 19:45:38",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "Politics and Government;Elections;United States Politics and Government;Musk, Elon;Rogan, Joe;Trump, Donald J;Government Efficiency Department (US)",
      column: null,
      byline: "By Jess Bidgood and Nicholas Nehamas",
      type: "Article",
      title:
        "Social Security and Sex Robots: Musk Veers Off Script With Joe Rogan",
      abstract:
        "Elon Musk’s three-hour interview with “The Joe Rogan Experience” offered a window into his worldview that was by turns crude and contradictory.",
      des_facet: [
        "Politics and Government",
        "Elections",
        "United States Politics and Government",
      ],
      org_facet: ["Government Efficiency Department (US)"],
      per_facet: ["Musk, Elon", "Rogan, Joe", "Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Elon Musk, left, recently gave his most extensive solo interview since the beginning of Trump’s new administration to the podcast host Joe Rogan, right.",
          copyright:
            "Eric Lee/The New York Times; Chris Unger/Zuffa LLC, via Getty Images",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/03/us/politics/03pol-on-politics-newsletter-rogan/03pol-on-politics-newsletter-rogan-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/us/politics/03pol-on-politics-newsletter-rogan/03pol-on-politics-newsletter-rogan-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/03/us/politics/03pol-on-politics-newsletter-rogan/03pol-on-politics-newsletter-rogan-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/58770621-d091-5611-9f6c-7f66344c3371",
      url: "https://www.nytimes.com/2025/03/04/opinion/trump-ukraine-putin-speech.html",
      id: 100000010031213,
      asset_id: 100000010031213,
      source: "New York Times",
      published_date: "2025-03-05",
      updated: "2025-03-05 00:46:37",
      section: "Opinion",
      subsection: "",
      nytdsection: "opinion",
      adx_keywords: "",
      column: null,
      byline: "By Thomas L. Friedman",
      type: "Article",
      title: "Trump Is Hiding Something on Ukraine",
      abstract:
        "When you don’t call things by their real name, there is usually a reason.",
      des_facet: [],
      org_facet: [],
      per_facet: [],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption: "",
          copyright: "Photo illustration by Ioulex for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/opinion-thepoint-friedman-joint-session-zblv/opinion-thepoint-friedman-joint-session-zblv-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/opinion-thepoint-friedman-joint-session-zblv/opinion-thepoint-friedman-joint-session-zblv-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/opinion-thepoint-friedman-joint-session-zblv/opinion-thepoint-friedman-joint-session-zblv-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/8abbaa37-06a7-5fb2-8fbf-87d4b9ab320f",
      url: "https://www.nytimes.com/2025/03/04/us/politics/trump-america-first.html",
      id: 100000010030154,
      asset_id: 100000010030154,
      source: "New York Times",
      published_date: "2025-03-04",
      updated: "2025-03-04 13:30:20",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "United States Politics and Government;International Relations;Protectionism (Trade);Trump, Donald J",
      column: null,
      byline: "By Luke Broadwater",
      type: "Article",
      title:
        "America vs. The World: Trump Shows How Far He Is Willing to Take ‘America First.’",
      abstract:
        "President Trump has frayed alliances across the globe with his words and actions.",
      des_facet: [
        "United States Politics and Government",
        "International Relations",
        "Protectionism (Trade)",
      ],
      org_facet: [],
      per_facet: ["Trump, Donald J"],
      geo_facet: [],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Since taking office, President Trump has picked fights with other nations that he believes are taking advantage of the United States.",
          copyright: "Eric Lee/The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04tariffs-news-trump-glcj/04tariffs-news-trump-glcj-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04tariffs-news-trump-glcj/04tariffs-news-trump-glcj-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/03/04/multimedia/04tariffs-news-trump-glcj/04tariffs-news-trump-glcj-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
    {
      uri: "nyt://article/51cea108-db92-54d6-9e13-b130ab2776f7",
      url: "https://www.nytimes.com/2025/03/03/us/politics/trump-canada-trade-tariffs.html",
      id: 100000010019276,
      asset_id: 100000010019276,
      source: "New York Times",
      published_date: "2025-03-03",
      updated: "2025-03-04 09:13:53",
      section: "U.S.",
      subsection: "Politics",
      nytdsection: "u.s.",
      adx_keywords:
        "United States International Relations;United States Politics and Government;Customs (Tariff);Protectionism (Trade);United States-Mexico-Canada Agreement;Trump, Donald J;Trudeau, Justin;Canada",
      column: null,
      byline: "By Alan Rappeport and Ian Austen",
      type: "Article",
      title: "What’s Behind Trump’s Love-Hate Relationship With Canada",
      abstract:
        "Canada is one of the United States’ largest trading partners, but President Trump wants to either take it or leave it.",
      des_facet: [
        "United States International Relations",
        "United States Politics and Government",
        "Customs (Tariff)",
        "Protectionism (Trade)",
        "United States-Mexico-Canada Agreement",
      ],
      org_facet: [],
      per_facet: ["Trump, Donald J", "Trudeau, Justin"],
      geo_facet: ["Canada"],
      media: [
        {
          type: "image",
          subtype: "photo",
          caption:
            "Prime Minister Justin Trudeau of Canada and President Trump in 2019 in London. As Mr. Trump prepares to push ahead with a new round of tariffs, he has expressed a special brand of loathing for Canada.",
          copyright: "Al Drago for The New York Times",
          approved_for_syndication: 1,
          "media-metadata": [
            {
              url: "https://static01.nyt.com/images/2025/02/28/multimedia/00dc-canada-lcjf/00dc-canada-lcjf-thumbStandard.jpg",
              format: "Standard Thumbnail",
              height: 75,
              width: 75,
            },
            {
              url: "https://static01.nyt.com/images/2025/02/28/multimedia/00dc-canada-lcjf/00dc-canada-lcjf-mediumThreeByTwo210.jpg",
              format: "mediumThreeByTwo210",
              height: 140,
              width: 210,
            },
            {
              url: "https://static01.nyt.com/images/2025/02/28/multimedia/00dc-canada-lcjf/00dc-canada-lcjf-mediumThreeByTwo440.jpg",
              format: "mediumThreeByTwo440",
              height: 293,
              width: 440,
            },
          ],
        },
      ],
      eta_id: 0,
    },
  ],
};
